include:
  - 'https://gitlab.lflab.cn/lflab_ci/gitlab-ci-templates/raw/master/julia-ci/v1.yml'

test:1:
  variables:
    julia_version: "1"
  extends:
    - .julia
    - .test

test:nightly:
  variables:
    julia_version: "nightly"
  extends:
    - .julia
    - .test
  allow_failure: true
